# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foundry < Formula
  desc ""
  homepage ""
  version "1.5.0"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://assets.foundry.crowdstrike.com/cli/latest/foundry_Darwin_arm64.tar.gz"
      sha256 "d7ce6d2b7e0a5efd9b92911fd5fa868bacf3b64b5221d3ce57fd5bae34e5ae69"

      def install
        bin.install "foundry"
      end
    end
    if Hardware::CPU.intel?
      url "https://assets.foundry.crowdstrike.com/cli/latest/foundry_Darwin_x86_64.tar.gz"
      sha256 "2a942faefbc967302914cfb3fff19d2c016f4d6c02eda26889883cbc3ac177f1"

      def install
        bin.install "foundry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://assets.foundry.crowdstrike.com/cli/latest/foundry_Linux_arm64.tar.gz"
      sha256 "f1b3d012a1b92ce6fb26cc28bec9d04982bbaaded432837bba697fba9e9575e4"

      def install
        bin.install "foundry"
      end
    end
    if Hardware::CPU.intel?
      url "https://assets.foundry.crowdstrike.com/cli/latest/foundry_Linux_x86_64.tar.gz"
      sha256 "6491b22bb4d3364c15adf028bf1faa1875a20e2fc087177d65670238ad41a62b"

      def install
        bin.install "foundry"
      end
    end
  end
end
