# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Foundry < Formula
  desc ""
  homepage ""
  version "2.1.0"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://assets.foundry.crowdstrike.com/cli/latest/foundry_Darwin_arm64.tar.gz"
      sha256 "6c7b61b23704590c5929e05b2b3e7cbe414e698f0a1e0f3fa43cc1d6ac9a27b6"

      def install
        bin.install "foundry"
      end
    end
    if Hardware::CPU.intel?
      url "https://assets.foundry.crowdstrike.com/cli/latest/foundry_Darwin_x86_64.tar.gz"
      sha256 "49e60d5fee8db2172956d9af079bd05871b3c07fd4929dd8ef4fb0ca016fc182"

      def install
        bin.install "foundry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://assets.foundry.crowdstrike.com/cli/latest/foundry_Linux_arm64.tar.gz"
      sha256 "0a85b3e4bd05e7b10851f8b5f484b590729f4e20856d041c602ab4ced303bec3"

      def install
        bin.install "foundry"
      end
    end
    if Hardware::CPU.intel?
      url "https://assets.foundry.crowdstrike.com/cli/latest/foundry_Linux_x86_64.tar.gz"
      sha256 "7a3abc85b31d0c3a3b3f497b1a16f611a0f4321202e550bb2e63997a6a42e780"

      def install
        bin.install "foundry"
      end
    end
  end
end
